/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TipoOperacion implements org.apache.thrift.TEnum {
  SUMA(0),
  RESTA(1),
  MULTIPLICACION(2),
  DIVISION(3),
  MEDIA(4);

  private final int value;

  private TipoOperacion(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TipoOperacion findByValue(int value) { 
    switch (value) {
      case 0:
        return SUMA;
      case 1:
        return RESTA;
      case 2:
        return MULTIPLICACION;
      case 3:
        return DIVISION;
      case 4:
        return MEDIA;
      default:
        return null;
    }
  }
}
