/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc_concurrente.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
sumatoria_auxiliar_1(int inicio, int final,  CLIENT *clnt)
{
	sumatoria_auxiliar_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.inicio = inicio;
	arg.final = final;
	if (clnt_call (clnt, SUMATORIA_AUXILIAR, (xdrproc_t) xdr_sumatoria_auxiliar_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
