/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc_concurrente.h"

bool_t
xdr_sumatoria_auxiliar_1_argument (XDR *xdrs, sumatoria_auxiliar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->inicio))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->final))
		 return FALSE;
	return TRUE;
}
