/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX 255

struct Operacion {
	float operando1;
	float operando2;
};
typedef struct Operacion Operacion;

struct Vector {
	int size;
	double datos[MAX];
};
typedef struct Vector Vector;

struct multiplicar_escalar_1_argument {
	Vector arg1;
	double arg2;
};
typedef struct multiplicar_escalar_1_argument multiplicar_escalar_1_argument;

#define CALCPROG 0x21000000
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  double * sumar_1(Operacion , CLIENT *);
extern  double * sumar_1_svc(Operacion , struct svc_req *);
#define RESTAR 2
extern  double * restar_1(Operacion , CLIENT *);
extern  double * restar_1_svc(Operacion , struct svc_req *);
#define MULTIPLICAR 3
extern  double * multiplicar_1(Operacion , CLIENT *);
extern  double * multiplicar_1_svc(Operacion , struct svc_req *);
#define DIVIDIR 4
extern  double * dividir_1(Operacion , CLIENT *);
extern  double * dividir_1_svc(Operacion , struct svc_req *);
#define MEDIA_VECTOR 5
extern  double * media_vector_1(Vector , CLIENT *);
extern  double * media_vector_1_svc(Vector , struct svc_req *);
#define MULTIPLICAR_ESCALAR 6
extern  Vector * multiplicar_escalar_1(Vector , double , CLIENT *);
extern  Vector * multiplicar_escalar_1_svc(Vector , double , struct svc_req *);
#define SUMATORIA 7
extern  long * sumatoria_1(int , CLIENT *);
extern  long * sumatoria_1_svc(int , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define RESTAR 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define MULTIPLICAR 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define DIVIDIR 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
#define MEDIA_VECTOR 5
extern  double * media_vector_1();
extern  double * media_vector_1_svc();
#define MULTIPLICAR_ESCALAR 6
extern  Vector * multiplicar_escalar_1();
extern  Vector * multiplicar_escalar_1_svc();
#define SUMATORIA 7
extern  long * sumatoria_1();
extern  long * sumatoria_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operacion (XDR *, Operacion*);
extern  bool_t xdr_Vector (XDR *, Vector*);
extern  bool_t xdr_multiplicar_escalar_1_argument (XDR *, multiplicar_escalar_1_argument*);

#else /* K&R C */
extern bool_t xdr_Operacion ();
extern bool_t xdr_Vector ();
extern bool_t xdr_multiplicar_escalar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
