/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_CONCURRENTE_H_RPCGEN
#define _CALC_CONCURRENTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sumatoria_auxiliar_1_argument {
	int inicio;
	int final;
};
typedef struct sumatoria_auxiliar_1_argument sumatoria_auxiliar_1_argument;

#define CALCCONCURPROG 0x22000000
#define CCV1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMATORIA_AUXILIAR 1
extern  int * sumatoria_auxiliar_1(int , int , CLIENT *);
extern  int * sumatoria_auxiliar_1_svc(int , int , struct svc_req *);
extern int calcconcurprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMATORIA_AUXILIAR 1
extern  int * sumatoria_auxiliar_1();
extern  int * sumatoria_auxiliar_1_svc();
extern int calcconcurprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sumatoria_auxiliar_1_argument (XDR *, sumatoria_auxiliar_1_argument*);

#else /* K&R C */
extern bool_t xdr_sumatoria_auxiliar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_CONCURRENTE_H_RPCGEN */
