/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operacion {
	float operando1;
	float operando2;
};
typedef struct Operacion Operacion;

#define CALCPROG 0x21000155
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  double * sumar_1(Operacion *, CLIENT *);
extern  double * sumar_1_svc(Operacion *, struct svc_req *);
#define RESTAR 2
extern  double * restar_1(Operacion *, CLIENT *);
extern  double * restar_1_svc(Operacion *, struct svc_req *);
#define MULTIPLICAR 3
extern  double * multiplicar_1(Operacion *, CLIENT *);
extern  double * multiplicar_1_svc(Operacion *, struct svc_req *);
#define DIVIDIR 4
extern  double * dividir_1(Operacion *, CLIENT *);
extern  double * dividir_1_svc(Operacion *, struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define RESTAR 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define MULTIPLICAR 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define DIVIDIR 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operacion (XDR *, Operacion*);

#else /* K&R C */
extern bool_t xdr_Operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
