/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_Operacion (XDR *xdrs, Operacion *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->operando1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->operando2))
		 return FALSE;
	return TRUE;
}
