/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdlib.h>


double
calculadora_basica(char *server, Operacion operandos, char operando)
{
	CLIENT *clnt;
	double * result_final;

#ifndef	DEBUG
	clnt = clnt_create (server, CALCPROG, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (server);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operando) {
		case '+': result_final = sumar_1(operandos, clnt); 				break;
		case '-': result_final = restar_1(operandos, clnt); 				break;
		case 'x': result_final = multiplicar_1(operandos, clnt); 		break;
		case '/': result_final = dividir_1(operandos, clnt); 				break;

		default: printf("Operando erróneo %c\n", operando); exit(EXIT_FAILURE); 			break;
	}

	if (result_final == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	return *result_final;
}

Vector * calculadora_compleja (char *server, Vector * vector, double escalar){

	CLIENT * clnt;
	double * media;
	Vector * vector_por_escalar;

	#ifndef	DEBUG
		clnt = clnt_create (server, CALCPROG, CALCVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (server);
			exit (1);
		}
	#endif	/* DEBUG */

	if ( vector == (Vector *) NULL) {
		printf("El vector es null\n");
		exit(EXIT_FAILURE);
	} else {

		media = media_vector_1(*vector, clnt);
		if (media == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}

		printf("La media es: %f\n", *media);

		vector_por_escalar = multiplicar_escalar_1(*vector, escalar, clnt);
		if (vector_por_escalar == (Vector *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return vector_por_escalar;
}


Vector * calculadora_concurrente (char *server, int n){

	CLIENT * clnt;
	int * resultado;

	#ifndef	DEBUG
		clnt = clnt_create (server, CALCPROG, CALCVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (server);
			exit (1);
		}
	#endif	/* DEBUG */



	resultado = sumatoria_1(n, clnt);
	if (resultado == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return (*resultado);
}

void leerVector(Vector * vector){
	printf("Introduce el número de elementos que tendrá el vector, siempre menor que %d\n", MAX);

	int size_vector = vector->size = 0;
	float nuevo_dato;

	scanf("%d", &size_vector);
	for (int i = 1; i <= size_vector; ++i){
		printf("Introduzca un elemento (%d de %d): ", i, size_vector);
		scanf("%f", &nuevo_dato);

		vector->datos[vector->size] = nuevo_dato;
		vector->size++;
	}
}

void mostrarVector (const Vector * vector){
	// Recorrer vector mostrando elementos uno a uno
	for (int i = 0; i < vector->size; i++){
		printf("%f ", vector->datos[i]);
	}
	printf("\n");
}

int
main (int argc, char *argv[])
{
	char *server;						// Declarar variable que guardara la ip del server
	Operacion operandos;				// Para almacenar los operandos de la operacion

	Vector vector;						// Vector de reales, realizar operaciones más complejas
	float escalar;				   // Escalar por el cual multiplicar el vector

	if (argc < 5) {
		printf ("usage: %s <server ip or DNS> <operando 1> <operador> <operando 2>\n", argv[0]);
		exit (EXIT_FAILURE);
	}

	server = argv[1];																				// Obtener direccion ip
	operandos.operando1 = atof(argv[2]);													// Obtener primer operando
	operandos.operando2 = atof(argv[4]);													// Obtener segundo operando
	char operador = argv[3][0];																// Obtener operador (solo un caracter)

	double resultado = calculadora_basica (server, operandos, operador);			// Ejecutar en servidor, con direccion, operandos y operador
	printf("El resultado es: %f\n\n\n", resultado);										// Mostrar resultado por pantalla

	printf("Vamos a operar un vector y un escalar\n");
	leerVector(&vector);

	printf("Introduzca un número entero o real: ");
	scanf("%f", &escalar);

	Vector * vector_multiplicado = calculadora_compleja(server, &vector, escalar);
	mostrarVector(vector_multiplicado);

	int n = 0;
	printf("\n\nVamos a calcular el sumatoria de un número, introduzca un entero: ");
	scanf("%d",&n);

	int sumatoria = calculadora_concurrente(server, n);
	printf("El resultado es: %d\n", sumatoria);


	exit (0);
}
